version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: cyberdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cyberdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis

  ai-service:
    build: ./ai-service
    container_name: flask_ai
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: